### ISSUE TITLE
error log: No Parser for java

### ISSUE THREAD

**Issue by gaocegege** [codacy/codacy-coverage-reporter#10]
Hi, When I run the command `codacy-coverage-reporter -l Java -r coverage.xml`, 

the output is confused:
```
2015-11-17 09:29:24,219 [info]  com.codacy Parsing coverage data...
2015-11-17 09:29:24,255 [error] com.codacy no parser for Java
```

And also, could I get the doc about the content of coverage.xml? It seems that there is no explanation about how to use..

**Comment by machadoit** [comment]
Hi, "we assume that coverage is previously configured for your project.".
This project does not handle the coverage generation, its purpose is to send that coverage to Codacy.
That said, you can check http://eclemma.org/jacoco/, on how to generate coverage.
You can also check out our https://github.com/codacy/codacy-api-java/blob/fix/docs/circle.yml where we have the automated process to generate and publish the coverage for a java project to Codacy.

**Comment by gaocegege** [comment]
Soga, Thks~

**Comment by xdevs23** [comment]
Thx
