### ISSUE TITLE
Integrate Java and Python Coverage Report

### ISSUE THREAD

**Issue by andresimbiose** [codacy/codacy-coverage-reporter#106]
Hello,
I have a project that part is writed in python and the other part is write in java.
I can generate the coverage.xml of these two parts separatly.
My questions is, how can i integrate these two coverage in codacy.
thanks in advance.
best regards,
André Luiz

**Comment by rtfpessoa** [comment]
You can push each report at a time to Codacy and they will both be showed in the UI. Since they are from different languages you don't even need to do a partial push.
