### ISSUE TITLE
 The provided coverage report generated an empty result

### ISSUE THREAD

**Issue by VladislavAntonyuk** [codacy/codacy-coverage-reporter#107]
I have generated test coverage (Cobertura, C#)

I execute the command in powershell
java -jar $reporterTool report -l CSharp -r "$testFile" -t $token

The response is :
11/02 10:00:11 ?[34mINFO ?[0;39m ?[36mcom.codacy.rules.ReportRules:48?[0;39m - Parsing coverage data from: C:\Users\user\source\repos\test\test-results\Tests.xml ...
11/02 10:00:14 ?[1;31mERROR?[0;39m ?[36mc.c.CodacyCoverageReporter$:28?[0;39m - The provided coverage report generated an empty result

**Comment by rtfpessoa** [comment]
@VladislavAntonyuk please reach our support team at `support at codacy dot com` or with the in app chat, please provide the xml report you passed to the tool so they can investigate what can be missing.
