### ISSUE TITLE
Debug mode enable shows token

### ISSUE THREAD

**Issue by wjfatuan** [codacy/codacy-coverage-reporter#120]
When running from the command line I see the debug output of the tool where my token is visible. Can I disable debug mode?

**Comment by IGFCoimbra** [comment]
Hi @wjfatuan 

I'm very sorry for the delay in getting back to you.

Can you please reach out to support@codacy.com with this report and a screenshot of what information is being displayed to you?

Regards,
Ivo

**Comment by ljmf00** [comment]
Hi @wjfatuan ,

By default, the `debug` mode is deactivated, and the project token is hidden. To activate it, you do `--debug`, so, make sure you don't have it on the running arguments. Please let me know if the problem persists.

Thanks,
