### ISSUE TITLE
--partial flag id beign ignored

### ISSUE THREAD

**Issue by javatlacati** [codacy/codacy-coverage-reporter#132]
### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)

Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.6 LTS
Release:	16.04
Codename:	xenial

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)

openjdk version "12.0.2" 2019-07-16
OpenJDK Runtime Environment (build 12.0.2+10)
OpenJDK 64-Bit Server VM (build 12.0.2+10, mixed mode, sharing)

### Expected Behavior

Please describe the expected behavior of the issue, starting from the first action.

1. I provide several jacoco.xml files with the --partial flag
2. I provide a final jacoco.xml file with a final parameter at the end
3. Code coverage should be summed up and displayed in codacy portal

### Actual Behavior

As previously detected in https://github.com/codacy/codacy-coverage-reporter/issues/88, maven multi module with jacoco shows only the code coverage from the last added module, the one with the "final".

### Reproducible Test Case

That's my current travis config:

```
language: java
cache:
  directories:
    - $HOME/.m2

services:
  - xvfb

before_install:
  - sudo apt-get install jq
  - wget -O ~/codacy-coverage-reporter-assembly-latest.jar $(curl https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r .assets[0].browser_download_url)

after_success:
  - mvn clean verify jacoco:report coveralls:report -B
  - ls target/site/
  - ls inventarios-service/target/
  - ls inventarios-desktop-testing-api/target/
  - java -jar ~/codacy-coverage-reporter-assembly-latest.jar report -l Java -r inventarios-service/target/site/jacoco/jacoco.xml --partial
  - java -jar ~/codacy-coverage-reporter-assembly-latest.jar report -l Java -r inventarios-restservice/target/site/jacoco/jacoco.xml --partial
  - java -jar ~/codacy-coverage-reporter-assembly-latest.jar report -l Java -r inventarios-desktop/target/site/jacoco/jacoco.xml --partial
  - java -jar ~/codacy-coverage-reporter-assembly-latest.jar report -l Java -r inventarios-desktop-testing-api/target/site/jacoco/jacoco.xml final

jdk:
  - openjdk12
```

You can check the project at https://github.com/javatlacati/Inventarios and my latest comit was 072b790eb13d09932b397169ccd9a96dc2fe2922

**Comment by ljmf00** [comment]
Hey @javatlacati ,

Have you tried do this instead?

```
java -jar ~/codacy-coverage-reporter-assembly-latest.jar report -l Java -r inventarios-service/target/site/jacoco/jacoco.xml --partial
java -jar ~/codacy-coverage-reporter-assembly-latest.jar report -l Java -r inventarios-restservice/target/site/jacoco/jacoco.xml --partial
java -jar ~/codacy-coverage-reporter-assembly-latest.jar report -l Java -r inventarios-desktop/target/site/jacoco/jacoco.xml --partial
java -jar ~/codacy-coverage-reporter-assembly-latest.jar report -l Java -r inventarios-desktop-testing-api/target/site/jacoco/jacoco.xml --partial
java -jar ~/codacy-coverage-reporter-assembly-latest.jar final
```

**Comment by javatlacati** [comment]
Yes, so much better now. Thank you.
