### ISSUE TITLE
reporter failed to upload report in trial version of codacy

### ISSUE THREAD

**Issue by BekyP** [codacy/codacy-coverage-reporter#140]
Hi,  after starting trial version of codacy, coverage-reporter stopped working (on free version works just fine). I am getting error below: 

```
2019-10-08 11:40:28,274 INFO             com.codacy Uploading coverage data... 
2019-10-08 11:40:28,862 ERROR            com.codacy Failed to upload report: API Error: failed to create coverage. 
Exited with code 1
```

I tried to add `export CODACY_API_BASE_URL=<Codacy_instance_URL>:16006` for enterprise version, but it didn`t help. Any suggestions?

**Comment by andreaTP** [comment]
Hi @BekyP , thanks for opening this issue.
Unfortunately we experienced an unplanned outage; everything should be back to normal now.

You can check our status page: https://status.codacy.com/

Feel free to re-open this ticket or a new one if you have additional problems uploading coverage that are not related to the outage!

**Comment by BekyP** [comment]
Thanks for quick answer, everything works fine now :+1:
