### ISSUE TITLE
[CY-2532] Add skip option to CircleCI orb

### ISSUE THREAD

**Issue by lolgab** [codacy/codacy-coverage-reporter#174]
The tool supports a skip flag to make sure the tool doesn't fail if the execution fails. Useful for forks scenarios.
We should add this flag to our CircleCI orb (check if we can automatically detect if we are running the flow on a fork and if it's useful)

**Comment by franciscodua** [comment]
This option was already added to the CircleCI Orb in [here](https://github.com/codacy/codacy-coverage-reporter/pull/240)
