### ISSUE TITLE
Problem using codacy-coverage-reporter with travis

### ISSUE THREAD

**Issue by v-stepanov** [codacy/codacy-coverage-reporter#20]
From today I have a problem with using codacy-coverage-reporter with travis. When it tries to install the reporter 
`sudo jpm install com.codacy:codacy-coverage-reporter:assembly`
it fails with error 
`Error`
`  0. [URLClient.send] http://repo.jpm4j.org/jsonrpc/2.0/jpm`
It worked few month before without any problems but from today it fails. I also tried to execute that jpm install locally on my computer - fails for me with the same error. Maybe jpm4j is down.

Example build: https://travis-ci.org/zalando/nakadi/builds/111450149

**Comment by pedrorijo91** [comment]
Hey !

We just noticed we are getting the same error. It seems to be some problem with `jpm` itself, but we'll check on that and investigate a solution as soon as possible

**Comment by dylanmcintyre** [comment]
Yeah JPM is getting 405s all over the place right now. I tried to compile and run codacy-coverage-reporter from source with sbt but am getting troubles. Can you give some clarification on that? Hopefully JPM isn't down too long though.

**Comment by machadoit** [comment]
Hi @dylanmcintyre 

We've just updated the README with the info you need to build from source: https://github.com/codacy/codacy-coverage-reporter#build-from-source
