### ISSUE TITLE
Improve Orb CircleCI Step Name

### ISSUE THREAD

**Issue by brunosmm** [codacy/codacy-coverage-reporter#220]
Hello,

Current the orb just have the command but not a name, which makes the CircleCI UI with a long and bad naming to understand what is happening on that step.

Current one:
<img width="1109" alt="image" src="https://user-images.githubusercontent.com/1554850/82910392-7d898f80-9f62-11ea-96b1-e8671f8676ea.png">
Here an example: https://app.circleci.com/pipelines/github/gsmainclusivetechlab/interop-sp-simulator/34/workflows/bfaf8a39-2acd-4499-ac16-e7e3e002a179/jobs/29

Add a name: parameter with some meaningful name, like "Sending report to Codacy", it will make a better step reporting in CircleCI.
The change should be in file https://github.com/codacy/codacy-coverage-reporter/blob/master/orbs/commands/send_report.yml line 19.

I am happy to send a pull request for this change, let me know if I can contribute to the project.

**Comment by josemiguelmelo** [comment]
Hello,

Thanks for the suggestion to improve our orb :+1: 
Feel free to open a pull request for the change, we would be glad to review it!

**Comment by brunosmm** [comment]
Hi @josemiguelmelo,

I send the pull request, you can find it here:
https://github.com/codacy/codacy-coverage-reporter/pull/221

Obrigado pelo suporte. 😄

**Comment by josemiguelmelo** [comment]
Hi @brunosmm,

Merged #221 and the CircleCI orb should already be updated with this improve.

Thanks for the suggestion of improvement and for the contribution 😄
