### ISSUE TITLE
When sending partial report let users know that a final signal is still required

### ISSUE THREAD

**Issue by franciscodua** [codacy/codacy-coverage-reporter#227]
Currently, users that want to send more than one report, or that use the partial flag see the following message at the end: `All coverage data uploaded.`.
Which might indicate the process of sending coverage is complete. It is not!

*Suggestion:* When the user still needs to send the final signal to Codacy, we should print `All coverage data uploaded. To complete the reporting process, call the coverage-reporter with a final flag. ./coverage-reporter final`

**Acceptance criteria:**
- Users that send partial coverage report get a message describing the required steps to complete process

**Comment by pauloribeiro-codacy** [comment]
May I suggest a small tweak to the copy?

`All coverage data uploaded. To complete the reporting process, call coverage-reporter with the final flag: ./coverage-reporter final`

**Comment by franciscodua** [comment]
> Is there still time for me to suggest a small tweak to the copy?
> 
> `All coverage data uploaded. To complete the reporting process, call coverage-reporter with the final flag: ./coverage-reporter final`

Sure, the proposed message is currently
```
To complete the reporting process, call the coverage-reporter with a final flag.
Check https://github.com/codacy/codacy-coverage-reporter#multiple-coverage-reports-for-the-same-language for more information.
```

What do you think?

You can check the PR in #228

**Comment by prcribeiro** [comment]
Thanks, I left my suggestion on the pull request. :+1:
