### ISSUE TITLE
Report fails with message "[error] com.codacy no parser for Java"

### ISSUE THREAD

**Issue by aecio** [codacy/codacy-coverage-reporter#23]
Currently, installation of `jpm` is failing due to some certificate problem:
```
$curl https://www.jpm4j.org/install/script | sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (77) error setting certificate verify locations:
  CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
```

After managing to install `jpm` manually and after installing the package `com.codacy:codacy-coverage-reporter:assembly`, the reporter is failing with the following message:
```
$ codacy-coverage-reporter -l Java -r coverage.xml
2016-05-27 17:27:57,669 [info]  com.codacy Parsing coverage data... 
2016-05-27 17:27:57,689 [error] com.codacy no parser for Java
```

**Comment by machadoit** [comment]
Hi @aecio,

Can you please open the issue in Codacy website support? There you can provide us with the project name and also please send us the coverage.xml that you are sending.

Thank you
