### ISSUE TITLE
[CY-2634] Getting error like Can't find any provider when trying to generate report using command line

### ISSUE THREAD

**Issue by sildisha-bacancy** [codacy/codacy-coverage-reporter#243]
first I run the phpunit testcases using this command
**./vendor/bin/phpunit --log-junit ~/phpunit/junit.xml tests** 

 then after i run this all command
**export CODACY_PROJECT_TOKEN=myprojecttoken**
**export CODACY_API_BASE_URL=http://localhost:8000/:16006**  (localhost:8000 is my api server url of local)
**bash <(curl -Ls https://coverage.codacy.com/get.sh)**

but I am getting this type of error...
it would be great if anyone suggests the solution.
![gitissue](https://user-images.githubusercontent.com/39408259/90642853-897aaa00-e250-11ea-8b92-31cd78a92482.png)

**Comment by lolgab** [comment]
The script tries to find the provider you are running the script from by analysing the environment variables.
Since you are running locally it can't use any CI provider facility to get the commit UUID.
So it uses the latest commit on the directory you launch the script in.
You can force a particular commit UUID by using the `--commit-uuid` parameter:

```bash
bash <(curl -Ls https://coverage.codacy.com/get.sh) report --commit-uuid YOUR_COMMIT_UUID
```

Hope this answers your question.
Lorenzo

**Comment by sildisha-bacancy** [comment]
hey, @lolgab thank you for helping me, It is working now. But now I have to configure Codacy with CircleCI but I am not able to understand how to configure it.
![circleciconfig](https://user-images.githubusercontent.com/39408259/90729716-9d6feb80-e2e4-11ea-8834-1453f8fbe1bc.PNG)
what i have to write here ?
  - coverage-reporter/send_report:
        coverage-reports: "report.xml,coverage.info"

**Comment by franciscodua** [comment]
Hi @sildisha-bacancy 

I think you're missing two spaces before `coverage-reports...` and before `project_token...` (keeping the consistency you have for the other steps. Apart from that, it's exactly like that.

Also, you can use the [CircleCI CLI](https://circleci.com/docs/2.0/local-cli/#validate-a-circleci-config) to validate your config file before committing. I find it very useful when changing these files.

**Comment by franciscodua** [comment]
I'm closing this issue, but please re-open it, or a new one if you still have any questions, problems, or suggestions.
