### ISSUE TITLE
Unknown argument

### ISSUE THREAD

**Issue by postalservice14** [codacy/codacy-coverage-reporter#26]
I'm trying to run the report like this:

```bash
codacy-coverage-reporter -l Java -r target/surefire-reports/*.xml
```

The output I'm getting is:

```bash
Error: Unknown argument 'target/surefire-reports/TEST-com.carsaver.adf.ValidatorTest.xml'
Error: Unknown argument 'target/surefire-reports/TEST-com.carsaver.adf.exception.ValidatorExceptionTest.xml'
```

Am I doing something wrong?  JaCoCo produces multiple XML files.

**Comment by machadoit** [comment]
Hi @postalservice14 

Our reporter does not support multiple report files at the moment, we need to add an aggregator for it. I added a task in our backlog for it, but we also accept PRs from the community.

**Comment by pedrorijo91** [comment]
Hi @postalservice14,

As a temporary solution I think it should be possible to aggregate multiple reports.

In Scala it is possible to aggregate multiple reports as you may see at https://github.com/scoverage/sbt-scoverage#multi-project-reports

For Java/Maven have you checked http://www.eclemma.org/jacoco/trunk/doc/report-aggregate-mojo.html ? As expected, it seems a common issue for developers using maven and jacoco: https://github.com/jacoco/jacoco/issues/18

I'm also not sure if aggregate reports should be a concern of this project. Until we find a solution, can you try these, and possibly other available solutions, and let us know if you were able to solve it?

**Comment by postalservice14** [comment]
Great, jacoco:report-aggregate worked.

Thanks

**Comment by ksclarke** [comment]
Just a note that report-aggregate only works if you're merging output from two different (sub)projects. If you have separate jacoco output from unit and integration tests from the same project, the Jacoco folks recommend using the merge goal. As far as I can tell though the merge goal only generates exec output and Codacy needs Jacoco XML output for its input.

**Comment by ksclarke** [comment]
Oh, I see now... I can run another report generation from the results of the merge goal.
