### ISSUE TITLE
[CY-3416] Provide an official Docker image

### ISSUE THREAD

**Issue by anais-codefresh** [codacy/codacy-coverage-reporter#280]
I was looking for a container image that can be used instead of calling the remote script in the cli.

It would be great for container-based CI/CD systems such as Google cloud builder, Codefresh, CircleCI, drone.io etc. if each version of the script would have its respective container image.

Examples of existing official images from other command-line tools which make their usage in CI/CD very easy
https://hub.docker.com/r/codeclimate/codeclimate
https://hub.docker.com/r/sonarsource/sonar-scanner-cli
https://hub.docker.com/r/golangci/golangci-lint

**Comment by josemiguelmelo** [comment]
Hi @anais-codefresh ,

Thanks for contributing and giving the suggestion to add a Docker image as an option to run our Coverage reporter 🙂

The official docker image was added on [this PR](https://github.com/codacy/codacy-coverage-reporter/pull/283) and it is now available on [Docker hub](https://hub.docker.com/r/codacy/codacy-coverage-reporter). You can check how to use it on [our documentation](https://docs.codacy.com/coverage-reporter/alternative-ways-of-running-coverage-reporter/#docker).
