### ISSUE TITLE
No parser for Java.

### ISSUE THREAD

**Issue by Todd-Davies** [codacy/codacy-coverage-reporter#32]
When I run the coverage reporter, I get:

```
export CODACY_PROJECT_TOKEN="<redacted>"; codacy-coverage-reporter -l Java -r coverage.xml
> 2016-08-05 19:00:09,319 [info]  com.codacy Parsing coverage data... 
> 2016-08-05 19:00:09,339 [error] com.codacy no parser for Java
```

This is after following the install method listed in the README.

**Comment by pedrorijo91** [comment]
Hi @Todd-Davies 

can you provide us a few more details?

* in which project is it happening ? (assuming it is open source)
* what's the sequence of commands you are using?
* what's your OS?
* what is the scala and sbt version of your project?

**Comment by Todd-Davies** [comment]
Hi @pedrorijo91,

This was my bad sorry! I didn't properly read the documentation and didn't realise that I had to run the coverage tests first.

Thanks,
Todd
