### ISSUE TITLE
[CY-4492] ARM Support?

### ISSUE THREAD

**Issue by trevorlinton** [codacy/codacy-coverage-reporter#327]
### Are you looking for help?

No, looking for the codacy coverage CLI to support ARM 64-bit platforms

### Scala Version (2.10.x / etc)

N/A

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)

Linux Ubuntu 21, ARM 64

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)

OpenJDK 1.11.x

### Library Dependencies

N/A

### Expected Behavior

Expected command to run

### Actual Behavior

```
     ______          __
1030
    / ____/___  ____/ /___ ________  __
1031
   / /   / __ \/ __  / __ `/ ___/ / / /
1032
  / /___/ /_/ / /_/ / /_/ / /__/ /_/ /
1007
  \____/\____/\__,_/\__,_/\___/\__, /
1008
                              /____/
1009

1010
  Codacy Coverage Reporter
1011

1012

1013
######################################################################## 100.0%
1014
 --> Downloading the codacy reporter codacy-coverage-reporter-linux... (12.2.0)
1015

1016
##                                                                         3.7%
1017
################                                                          23.4%
1018
#####################################                                     51.5%
1019
############################################################              84.6%
1020
######################################################################## 100.0%
1021
/dev/fd/63: line 156: /home/pi/.cache/codacy/coverage-reporter/12.2.0/codacy-coverage-reporter: cannot execute binary file: Exec format error
1022

```

### Reproducible Test Case

Run the codacy coverage tool on any arm64 bit platform.

**Comment by franciscodua** [comment]
Hi @trevorlinton 
Does the Java version work in that scenario?
We'll take the ARM support request to our internal product board, but it's not in our immediate backlog 😬 .

Let us know if the Java version works for you, or if you have any other problem

**Comment by franciscodua** [comment]
I'm closing this. As I said, we already have this in our long-term backlog. But if you have any other concerns you can re-open this issue

**Comment by marvinruder** [comment]
I have the same issue on my arm64 machine. The Java version works fine, but it is not automatically chosen by the bash script. I will suggest some changes that should make it possible to use the script on an arm64 machine as well.
