### ISSUE TITLE
[CY-5948] Add a Security Policy

### ISSUE THREAD

**Issue by cschroed-usgs** [codacy/codacy-coverage-reporter#370]
GitHub has [a security policy feature](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository). Would Codacy be interested in establishing a security policy?

**Comment by stefanvacareanu7** [comment]
Hi there,

Thanks for reaching out to our community!

I am going to pass your proposal to the Reliability Team and return with a response as soon as I have it.

Best,
Stefan
