### ISSUE TITLE
[CY-5950] Adopt a software composition analysis solution

### ISSUE THREAD

**Issue by cschroed-usgs** [codacy/codacy-coverage-reporter#373]
#372 and #369 illustrate the need to adopt a software composition analysis solution. Software composition analysis solutions automatically identify dependencies that are vulnerable and/or out of date. Some solutions even automatically propose remediations and/or upgrades.

You may find it helpful to consult [The Linux Foundation's Open Guide To Evaluating Software Composition Analysis Tools](https://www.linuxfoundation.org/tools/an-open-guide-to-evaluating-software-composition-analysis-tools/) .

**Comment by stefanvacareanu7** [comment]
Hi there,

Thank you for your proposal. I have passed it further to our Reliability Team and I'll return as soon as I have an update.

Best,
Stefan

**Comment by stefanvacareanu7** [comment]
No further action can be made for moment, closing issue
