### ISSUE TITLE
[DOCS-381] Add troubleshooting for "Failed to upload coverage report ... connect timed out"

### ISSUE THREAD

**Issue by prcr** [codacy/codacy-coverage-reporter#383]
If you're getting a `Failed to upload coverage report ... connect timed out` error while uploading your coverage data to Codacy it can mean that you're uploading large coverage reports and that call to the Codacy API is timing out.

To solve the issue, you should use the flag `--http-timeout` to specify a larger timeout. For example, to specify a timeout of 10 seconds:

```
bash <(curl -Ls https://coverage.codacy.com/get.sh) report --http-timeout 10000 -r coverage.xml
```

The documentation page [Troubleshooting common issues](https://docs.codacy.com/coverage-reporter/troubleshooting-common-issues/) should be updated to include this scenario. See [CY-6072](https://codacy.atlassian.net/browse/CY-6072) for more background information.

**Comment by prcr** [comment]
Currently, the Codacy Coverage Reporter GitHub Action doesn't support the `--http-timeout`, so these troubleshooting instructions apply only to the "regular" CLI.

**Comment by rahul181198** [comment]
how to add this  flag in the gradle task format

**Comment by prcr** [comment]
Hello @rahul181198,

I haven't actually tested this, but by looking at our [example Gradle tasks](https://docs.codacy.com/coverage-reporter/alternative-ways-of-running-coverage-reporter/#gradle-task) I expect that adding the flag like this should work:

```
[...]

task sendCoverageToCodacy(type: JavaExec, dependsOn: jacocoTestReport) {
    main = "com.codacy.CodacyCoverageReporter"
    classpath = configurations.codacy
    args = [
            "report",
            "--http-timeout",
            "10000",
            "-l",
            "Java",
            "-r",
            "${buildDir}/reports/jacoco/test/jacocoTestReport.xml"
    ]
}
```

Let us know if this example is enough to made it work or if you still need help.

**Comment by rahul181198** [comment]
I get this in exception . When I try above syntax 

Unrecognized argument: --http-timeout

**Comment by prcr** [comment]
I verified that the last Codacy Coverage Reporter version that we published to the Maven Central Repository is quite outdated and doesn't include the `--http-timeout` flag yet (it was added on version [12.3.0](https://github.com/codacy/codacy-coverage-reporter/releases/tag/12.3.0)):

https://search.maven.org/artifact/com.codacy/codacy-coverage-reporter/7.1.0/jar

I'm checking this internally with the Engineering teams and I'll let you know once I have an update.

**Comment by rahul181198** [comment]
I already tried the same syntax but it gives me log that it is sending the coverage report but I get no log about it being successful and being received like I used to get before .My build though is  successful but i see no coverage in dashboard.

**Comment by prcr** [comment]
@rahul181198, it's possible that there's now a different issue that may be causing that. Could you please reach out to support@codacy.com providing the details on how you're running the Codacy Coverage Reporter and the resulting logs so that our Support team can help you troubleshoot your setup?
