### ISSUE TITLE
[CY-6234] Wrong checksum for codacy-coverage-reporter-linux 13.9.14 in GithubAction

### ISSUE THREAD

**Issue by michaelhglass** [codacy/codacy-coverage-reporter#393]
We're running the "standard" Codacy Github Integration in our project and receive a checksum error since release of 13.9.14:

`--> Downloading the codacy reporter codacy-coverage-reporter-linux... (13.9.14)
######################################################################## 100.0%
--> Checking checksum...
#=#=#                                                                         
######################################################################## 100.0%
--> Expected checksum
4d8299f9fb58aedaee0c2e[294](https://github.com/SDARG/opt4j/runs/6879278310?check_suite_focus=true#step:7:297)8b0cfbdc39be3b0620e64211b8a22bbca607d05a3164edb753b9c5e6128dad56b14d89a1fd4c5b2d56a64c43b08fe0fc384ccd7  codacy-coverage-reporter-linux
--> Actual checksum
758614c368566b4830a19e072e3d4a205be0c058a87c2813d67b8f4e60516fb4c76915752dbd0ee75e0203de847ed1b5bb03917f6d336d554424af97dde3b560  codacy-coverage-reporter-linux
sha512sum: WARNING: 1 computed checksum did NOT match`

Example can be found here: https://github.com/SDARG/opt4j/actions/runs/2494419802

Sorry if this is the wrong place for reporting, feel free to delete if the problem is on my side.
Cheers

**Comment by markus-dobel-fioneer** [comment]
Tried to debug a little, and what I've found is this:

the `get.sh` script used in the action downloads the reporter binary from 
  https://artifacts.codacy.com/bin/codacy-coverage-reporter/13.9.14/codacy-coverage-reporter-linux 
and the checksum file from 
  https://github.com/codacy/codacy-coverage-reporter/releases/download/13.9.14/codacy-coverage-reporter-linux.SHA512SUM

These do not match indeed, while the SHA512SUM matches what is downloadable from github releases, 
  https://github.com/codacy/codacy-coverage-reporter/releases/download/13.9.14/codacy-coverage-reporter-linux
  
So, the binaries published on artifacts.codacy.com and github.com are not the same.

**Comment by markus-dobel-fioneer** [comment]
Workaround for github actions:

```yaml
env:
  CODACY_REPORTER_VERSION: 13.9.13
```

This env variable is then picked up by get.sh within the reporter action (something I did not know, tbh)

**Comment by pedrocodacy** [comment]
@michaelhglass thank you for the issue report, we are on it 🙇 

also may thanks @markus-dobel-fioneer 🙇  that should fix it, we had an issue publishing the latest version that caused the checksums to misalign - we are working on a definitive fix for you to be able to use the latest version 🙏

**Comment by michaelhglass** [comment]
13.9.15 seems to resolve the issue. Thanks for the quick fix and many  thanks in general for providing this magnificent tool!
