### ISSUE TITLE
Can not install jpm

### ISSUE THREAD

**Issue by rockerhieu** [codacy/codacy-coverage-reporter#43]
### Scala Version (2.10.x / etc)
2.12.1

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)
MacOS 10.12.2

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)

java version "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)

### Expected Behavior

This command should install `jpm` into my machine:
```bash
curl https://www.jpm4j.org/install/script | sh
```

### Actual Behavior

```
curl: (60) SSL certificate problem: certificate has expired
More details here: https://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
```

I tried `-k` but there was another error:
```bash
curl -k https://www.jpm4j.org/install/script | sh
```
```
Error
  0. [JustAnotherPackageManager.<init>] Failed java.lang.IllegalArgumentException: Could not create directory /Library/Java/PackageManager
```

**Comment by rockerhieu** [comment]
I've followed the instruction at http://jpm4j.org/#!/md/macos and could install jpm normally. Perhaps you should update the README.md.

**Comment by pedrorijo91** [comment]
Hey @rockerhieu, we'll confirm this as soon as possible. In the meanwhile, feel free to do a PR with the alternative installation guide that worked for you

Thanks,
Pedro

**Comment by rtfpessoa** [comment]
Updated https://github.com/codacy/codacy-coverage-reporter#failed-to-install-jpm-on-mac-os
