### ISSUE TITLE
[CY-6692] Feature Request: Support `--codacy-reporter-version` argument

### ISSUE THREAD

**Issue by JBallin** [codacy/codacy-coverage-reporter#439]
The available options are listed [here](https://github.com/codacy/codacy-coverage-reporter/blob/master/src/main/scala/com/codacy/configuration/parser/ConfigurationParser.scala). While `codacyApiBaseUrl` is supported as an alternative to setting `CODACY_API_BASE_URL`, `codacyReporterVersion` is missing as an alternative to setting `CODACY_REPORTER_VERSION`.

I prefer to be consistent with using the CLI arguments (stylistically), instead of having some of them be controlled via env vars.

**Current**

```sh
export foo=1
report --bar 2
```

**Desired**

```sh
report --foo 1 --bar 2
```

**Comment by stefanvacareanu7** [comment]
Hi there,

Thanks for reaching our community!

This request is not our priority, so the team won't work on it.

I appreciate your initiative and invite you to create a new PR with the update.

Best,
Stefan
