### ISSUE TITLE
JPM install fails

### ISSUE THREAD

**Issue by micheljung** [codacy/codacy-coverage-reporter#46]
Not sure whether this is something you can/need to fix or if it's on JPM's side, however...

All my projects suddenly fail to report, [like this one](https://travis-ci.org/FAForever/faf-java-commons/builds/217480165), because `jpm install` throws an error:

```
$ curl -sL https://github.com/jpm4j/jpm4j.installers/raw/master/dist/biz.aQute.jpm.run.jar >jpm4j.jar
before_install.3
$ java -jar jpm4j.jar -u init
Home dir      /home/travis/jpm
Bin  dir      /home/travis/jpm/bin
$ ~/jpm/bin/jpm install com.codacy:codacy-coverage-reporter:assembly
Error
  0. [URLClient.send] http://repo.jpm4j.org/jsonrpc/2.0/jpm
```

**Comment by rtfpessoa** [comment]
Check the README.md for some alternatives. We have some community contributed gradle tasks and also a maven plugin. Also you can always use the jar here https://github.com/codacy/codacy-coverage-reporter#run-with-jar

**Comment by micheljung** [comment]
Great! The Gradle task works for me, thank you.
However, for some people this may not be an option :) At least as long as it's on the readme page, I think you want to figure out why it doesn't work anymore?

**Comment by rtfpessoa** [comment]
Someone reported that JPM is not being maintained anymore. Since it already gave us lots of headaches we are already looking for alternatives. If you know any let me know.

**Comment by aharonha** [comment]
We are using TravisCI and our pull requests are failing.
Is there another solution rather than JPM?

**Comment by rtfpessoa** [comment]
As I pointed in https://github.com/codacy/codacy-coverage-reporter/issues/46#issuecomment-290910245 there are a couple of options to choose from.
