### ISSUE TITLE
[TS-511] 13.13.3 is broken

### ISSUE THREAD

**Issue by BradleyUffner** [codacy/codacy-coverage-reporter#464]
Since 13.13.3 was merged 2 hours ago, our bitbucket pipelines have been broken with the following error:

> bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r TestResults/coverage.cobertura.xml
>      ______          __
>     / ____/___  ____/ /___ ________  __
>    / /   / __ \/ __  / __ `/ ___/ / / /
>   / /___/ /_/ / /_/ / /_/ / /__/ /_/ /
>   \____/\____/\__,_/\__,_/\___/\__, /
>                               /____/
>   Codacy Coverage Reporter
> ######################################################################## 100.0%
>  --> Downloading the codacy reporter codacy-coverage-reporter-linux... (13.13.3)
> ##############################################################            87.5%
> ######################################################################## 100.0%
>  --> Checking checksum...
> ######################################################################## 100.0%
>  --> Expected checksum
> c3175c1ebd225fb08128b17bb74f4623195e95629eb249bd1c62b4e9c9714c5fdc491846c15254e2db6f1c931489e61f1daca5ef0d0d98137b31ef837783350d  codacy-coverage-reporter-linux
>  --> Actual checksum
> c3175c1ebd225fb08128b17bb74f4623195e95629eb249bd1c62b4e9c9714c5fdc491846c15254e2db6f1c931489e61f1daca5ef0d0d98137b31ef837783350d  codacy-coverage-reporter-linux
> codacy-coverage-reporter-linux: OK
> chmod: cannot access '/root/.cache/codacy/coverage-reporter/13.13.3/codacy-coverage-reporter': No such file or directory
>  --> Failed!
>

**Comment by amir20001** [comment]
Seeing the same issue across the board

**Comment by fedebabrauskas** [comment]
Same issue here!
https://github.com/codacy/codacy-coverage-reporter-action/issues/73

**Comment by DMarinhoCodacy** [comment]
Hello all,

It will be solved today.

**Comment by DMarinhoCodacy** [comment]
Hello again,

Can you try again? All the changes made today were reverted.

Sorry again for any inconvenience.

**Comment by BradleyUffner** [comment]
Pipelines are working for us again. Thank you for the fix!
