### ISSUE TITLE
[TCE-969] Pull request and push are failed: project or account API token not found

### ISSUE THREAD

**Issue by vitalijr2** [codacy/codacy-coverage-reporter#502]
I am using Codacy actions for many my projects, but since March I have met the issue of Coverate Reporter.

It says that cannot find project token while other Codacy's action work well.
![screenshot_2024-05-13_07-50-59_542722647](https://github.com/codacy/codacy-coverage-reporter/assets/368917/1348d8bd-b7b4-4513-b363-d61fa2af767a)

The issue
![screenshot_2024-05-13_07-45-54_473328804](https://github.com/codacy/codacy-coverage-reporter/assets/368917/0365982d-7cca-4e97-b89c-942ce2a86a3c)

Action source is here
https://github.com/vitalijr2/tidy-chat/blob/main/.github/workflows/codacy.yml

Related issue:
[TCE-897 Pull-Request from contributors can't find CODACY_PROJECT_TOKEN](https://github.com/codacy/codacy-coverage-reporter-action/issues/84)

[TCE-897]: https://codacy.atlassian.net/browse/TCE-897?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by vitalijr2** [comment]
There is strange behavior of the action:

PR [Bump mockito.version from 5.11.0 to 5.12.0](https://github.com/vitalijr2/aws-lambda-slf4j/pull/19):
- first run was failed https://github.com/vitalijr2/aws-lambda-slf4j/actions/runs/9051167759/job/24867381889
- then I played with `secrets` option but reverted changed back
- last run was successful https://github.com/vitalijr2/aws-lambda-slf4j/actions/runs/9061334934/job/24892913096 but it only increments a dependency version https://github.com/vitalijr2/aws-lambda-slf4j/pull/19/files

**Comment by asturio** [comment]
Is it still working for you?

**Comment by vitalijr2** [comment]
Last Sunday I met this issue on my ijhttp-tools repo, see PRs [1](https://github.com/vitalijr2/ijhttp-tools/pull/22 "Bump spring-boot.version from 3.2.5 to 3.3.0"), [2](https://github.com/vitalijr2/ijhttp-tools/pull/21 "Bump org.apache.maven:maven-plugin-api from 3.9.6 to 3.9.7"), [3](https://github.com/vitalijr2/ijhttp-tools/pull/20 "Bump mockito.version from 5.11.0 to 5.12.0").

Then I update the development branch (base for these PRs): cha versions both **codacy/codacy-analysis-cli-action** and **codacy/codacy-coverage-reporter-action** to `v4.4.1` and `v1.3.0` respectively. Then merged changes back to branches - all workflows done well.

I will not close the PR yet - maybe it will be useful for you.

**Comment by vitalijr2** [comment]
Maybe one picture better then 1000 words :)
![screenshot_2024-05-27_16-41-50_550688558](https://github.com/codacy/codacy-coverage-reporter/assets/368917/93dace1f-7152-4115-a2bc-a2121511f7fa)

**Comment by vitalijr2** [comment]
I was wrong: it happend again. And again. Even with updated versions for both actions: coverage and security check.

Codacy Coverage Reporter is failed on missed API token
https://github.com/vitalijr2/aws-lambda-slf4j/actions/runs/9535472577/job/26281254400?pr=30
https://github.com/vitalijr2/aws-lambda-slf4j/actions/runs/9535472459/job/26281254992?pr=30

But some other Codacy actions can find it!
https://github.com/vitalijr2/aws-lambda-slf4j/actions/runs/9535472577/job/26281254484?pr=30
https://github.com/vitalijr2/aws-lambda-slf4j/actions/runs/9535472459/job/26281255094?pr=30
https://github.com/vitalijr2/aws-lambda-slf4j/pull/30/checks?check_run_id=26281290537
https://github.com/vitalijr2/aws-lambda-slf4j/pull/30/checks?check_run_id=26281290518
etc.

Also Codacy Static Code Analysis fails
https://github.com/vitalijr2/aws-lambda-slf4j/pull/30/checks?check_run_id=26281275633
but Codacy says nothing what is happend
https://app.codacy.com/gh/vitalijr2/aws-lambda-slf4j/pull-requests/30
and logs are empty
![screenshot_2024-06-17_13-40-11_371128510](https://github.com/codacy/codacy-coverage-reporter/assets/368917/06ebe309-c8c1-4213-80d3-ed07f1dc2963)

**Comment by vitalijr2** [comment]
Now I have three PR from dependency bot
https://github.com/vitalijr2/aws-lambda-slf4j/pull/30
https://github.com/vitalijr2/aws-lambda-slf4j/pull/29
https://github.com/vitalijr2/aws-lambda-slf4j/pull/28
and all of them are failed because of Codacy Coverage Reporter (that says he could not find project API token)
and Codacy Static Code Analysis (that says nothing)

**Comment by vitalijr2** [comment]
Another two cases, same issues with reporter and static code analyser
https://github.com/vitalijr2/ijhttp-tools/pull/32
https://github.com/vitalijr2/ijhttp-tools/pull/31

**Comment by vitalijr2** [comment]
Uhhh, looks like it GitHub feature especially for dependebot:

> When a Dependabot event triggers a workflow, the only secrets available to the workflow are Dependabot secrets. 
See:
* [Dependabot triggered Actions cant access secrets or use a writable token](https://github.com/dependabot/dependabot-core/issues/3253)
* [Automating Dependabot with GitHub Actions: Accessing secrets](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions#accessing-secrets)

I have copied the CODACY_PROJECT_TOKEN Settings => Secrets and variables => Dependabot secrets then re-run jobs and all are green.

**Comment by vitalijr2** [comment]
Uhhh, looks like it GitHub feature especially for dependebot:

> When a Dependabot event triggers a workflow, the only secrets available to the workflow are Dependabot secrets. 
See:
* [Dependabot triggered Actions cant access secrets or use a writable token](https://github.com/dependabot/dependabot-core/issues/3253)
* [Automating Dependabot with GitHub Actions: Accessing secrets](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions#accessing-secrets)

I have copied the CODACY_PROJECT_TOKEN Settings => Secrets and variables => Dependabot secrets then re-run coverage jobs and all are green.
The static code analyser's issue still exists.

**Comment by asturio** [comment]
> Uhhh, looks like it GitHub feature especially for dependebot:
> 
> > When a Dependabot event triggers a workflow, the only secrets available to the workflow are Dependabot secrets.
> > See:
> 
>     * [Dependabot triggered Actions cant access secrets or use a writable token](https://github.com/dependabot/dependabot-core/issues/3253)
> 
>     * [Automating Dependabot with GitHub Actions: Accessing secrets](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions#accessing-secrets)
> 
> 
> I have copied the CODACY_PROJECT_TOKEN Settings => Secrets and variables => Dependabot secrets then re-run coverage jobs and all are green. The static code analyser's issue still exists.

Oh, THIS makes sense.
