### ISSUE TITLE
Specify if multi-modules are supported

### ISSUE THREAD

**Issue by gortiz** [codacy/codacy-coverage-reporter#52]
This is not a issue with the code but with the documentation (mainly the README.md)

It doesn't say anywhere if the product support multi module projects and if it does, how to configure it.

With multi-module projects I mean project with hierarchies. For example on Maven it is easy and common to have a pom project on the root of the repo and several sub modules/projects on different folders. Each module has its own jacoco.xml file, so... does codacy-coverage-reporter support to add several jacoco.xml files? does it only support one? It isn't specify anywhere (or at least I was not able to find it). I think it should be explicitly said on the README.md

**Comment by rtfpessoa** [comment]
This project is currently not concerned with multi-modules.
It just sends coverage parsed from one XML file either in JaCoCo or Cobertura format.
If you use are referring to the maven plugin, you need to ask in https://github.com/halkeye/codacy-maven-plugin.

Usually merging is handled by the tool you are using to generate the actual coverage.

**Comment by gortiz** [comment]
I don't think you understood me.

- IMHO if mult-modules are not supported, the README.md (or somewhere else on the documentation) should say that.
- I used maven as an example, but it is not limited or even related with maven projects. It is about specifying if multi projects are supported or not.
- The maven project you talk about delegates on codacy-coverage-reporter, so if the reporter doesn't support multi-projects, the maven project neither does it.
- I don't know about other building tools (Gradle, etc), but at least the jacoco maven plugin does generate one jacoco.xml file per module and the reporting platform is the one that merges it. This is what SonarQube and Codecov do and I would expect that from Codacy.

**Comment by rtfpessoa** [comment]
Why not use merge from JaCoCo http://www.eclemma.org/jacoco/trunk/doc/merge-mojo.html for example?

Our idea is mainly to not duplicate the tools code since they usually handle it internally.

**Comment by gortiz** [comment]
It seems great! I didn't know that mojo. But my point is still there... Would not be cool to to have a section on the README.md that specifies what to do if you have a multi module project?

**Comment by rtfpessoa** [comment]
Sure. I will add a section to explain the situation.
