### ISSUE TITLE
Support for AWS CodeBuild (from CodePipeline)

### ISSUE THREAD

**Issue by thaddeusdiamond-smartercloud** [codacy/codacy-coverage-reporter#58]
### Are you looking for help?

I would love for AWS CodeBuild environment variables related to CI commit hash be picked up.  The relevant variable here is ``CODEBUILD_RESOLVED_SOURCE_VERSION``.  The fact that there is no git directory here is a known bug documented at https://forums.aws.amazon.com/thread.jspa?threadID=244197.

### Scala Version (2.10.x / etc)

n/a

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)

n/a

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)

n/a

### Library Dependencies

AWS CodeBuild

### Expected Behavior

Please describe the expected behavior of the issue, starting from the first action.

1. AWS CodeBuild runs a build triggered by CodePipeline
2. The CodacyCoverageReporter class detects the correct env variable
3. Do not need to use "--commitUUID" flag

### Actual Behavior

Environment variable is not currently picked up, upload to Codacy fails in the pipeline.

### Reproducible Test Case

I have a private repo I am testing this on.

**Comment by thaddeusdiamond-smartercloud** [comment]
Submitted pull request #57 to track this issue.

**Comment by pedrorijo91** [comment]
closed by #57
