### ISSUE TITLE
The help text for --commitUUID and --prefix text is swapped

### ISSUE THREAD

**Issue by ddimtirov** [codacy/codacy-coverage-reporter#60]
https://github.com/codacy/codacy-coverage-reporter/blob/fb5d6236c267c0ae00d59ff7176b9185ff8a1aee/src/main/scala/com/codacy/CodacyCoverageReporter.scala#L117

**Comment by pedrorijo91** [comment]
Hey @ddimtirov,

Thanks for pointing out the bug. Would you like to contribute by doing a PR? :)

**Comment by ddimtirov** [comment]
I cant justify babysitting a PR for such a low value change. Fix it if you
feel like, leave it if you have more urgent things to do ;-)
