### ISSUE TITLE
Better error log message

### ISSUE THREAD

**Issue by benmccann** [codacy/codacy-coverage-reporter#62]
### Scala Version (2.10.x / etc)

N/A

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)

Ubuntu 16.04

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)

1.8.0_131

### Library Dependencies

N/A

### Actual Behavior

I'm getting the error message:

>com.codacy Failed to upload report: not found

### Expected Behavior

This error message could be improved in several ways. Firstly, I'm not 100% sure whether "not found" is referring to the JaCoCo report file, my Codacy account, a 404 http response in trying to find the Codacy upload endpoint, etc..

As far as I can tell, I've pointed it at a valid file that exists. If it said something like "file not found at /user/abc/project/target/report/jacoco.xml" then I'd have a better idea whether the tool is somehow looking at the wrong path. I've run `ls` in my Travis build and it seems to indicate the file is present

    $ ls aggregate/target/site/jacoco-aggregate/jacoco.xml
    aggregate/target/site/jacoco-aggregate/jacoco.xml

### Reproducible Test Case

I have setup Codacy for https://github.com/jtablesaw/tablesaw

You can see the `com.codacy Failed to upload report: not found` message on recent Travis builds such as https://travis-ci.org/jtablesaw/tablesaw/builds/272714268?utm_source=github_status&utm_medium=notification

**Comment by benmccann** [comment]
@pedrorijo91 @rtfpessoa any ideas?

**Comment by rtfpessoa** [comment]
It seems like a problem with the token. Can you double check that you have a variable in the env named `CODACY_PROJECT_TOKEN` with the correct value you copied from Codacy?

**Comment by benmccann** [comment]
Thanks. That was a good tip.

I originally followed these instructions and couldn't get it to work: https://docs.travis-ci.com/user/environment-variables/#Defining-encrypted-variables-in-.travis.yml
I just got fixed it by following these instructions instead: https://docs.travis-ci.com/user/environment-variables/#Defining-Variables-in-Repository-Settings

I'll leave this issue open with a few suggestions.
It would be helpful to put a link to https://docs.travis-ci.com/user/environment-variables/#Defining-Variables-in-Repository-Settings on https://support.codacy.com/hc/en-us/articles/207279819-Coverage.

Also, the error message `com.codacy Failed to upload report: not found` was really misleading. I thought it couldn't find the report. It didn't indicate to me at all that there was an issue with my token.

**Comment by DReigada** [comment]
Version [4.0.0](https://github.com/codacy/codacy-coverage-reporter/releases/tag/4.0.0) of the reporter improves its feedback on usual error cases, including this one.
As such I'm going to close this issue.

Thanks for the feedback @benmccann.
