### ISSUE TITLE
Support Heroku CI Commit SHA

### ISSUE THREAD

**Issue by acekevin** [codacy/codacy-coverage-reporter#72]
Heroku CI exposes `HEROKU_TEST_RUN_COMMIT_VERSION` while running tests. It is possible to force the UUID by setting `--commit-uuid HEROKU_TEST_RUN_COMMIT_VERSION`, but would it be possible to support it internally along with the other environment variables like `TRAVIS_COMMIT` ?

https://devcenter.heroku.com/articles/heroku-ci#configuration-using-app-json

**Comment by rtfpessoa** [comment]
Hi @acekevin feel free to send a PR. @DReigada can you help identify the place where it would need to be added?

**Comment by DReigada** [comment]
Hi @acekevin you just need to add the variable in this function: https://github.com/codacy/codacy-coverage-reporter/blob/bf8c27eb3a1cb97fe0d87082a727b110ef548207/src/main/scala/com/codacy/rules/ConfigurationRules.scala#L108

**Comment by rtfpessoa** [comment]
There was a problem in the tests and they were not being run as expected. This lead to a buggy release. Sorry about this. I will try to fix it soon but seems like a limitation from the tool I was using to release the binary. I will try to find an alternative for the jar in the meanwhile.

Sorry for the confusion.

**Comment by rtfpessoa** [comment]
Fixed in https://github.com/codacy/codacy-coverage-reporter/releases/tag/6.0.0
