### ISSUE TITLE
Travis builds are failing because of rate-limits on api.github.com

### ISSUE THREAD

**Issue by rshivane** [codacy/codacy-coverage-reporter#75]
We are using travis to make our builds.
Travis.yml has the typical instructions to download latest codacy reporter. See: https://github.com/rshivane/JInsight/blob/master/.travis.yml#L47

Of late our builds are failing because of rate limits on api.github.com. See the `X-RateLimit` headers from the curl output below.

Build passes when we retry the build after sometime (after the rate limit reset occurs).

The install/usage instructions need to use a more reliable mechanism.

```
0.17s$ wget -O ~/.codacy/reporter/codacy-reporter-latest.jar $(curl -v https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r .assets[0].browser_download_url)
* Hostname was NOT found in DNS cache
*   Trying 192.30.253.117...
* Connected to api.github.com (192.30.253.117) port 443 (#0)
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* SSLv3, TLS handshake, Client hello (1):
} [data not shown]
* SSLv3, TLS handshake, Server hello (2):
{ [data not shown]
* SSLv3, TLS handshake, CERT (11):
{ [data not shown]
* SSLv3, TLS handshake, Server key exchange (12):
{ [data not shown]
* SSLv3, TLS handshake, Server finished (14):
{ [data not shown]
* SSLv3, TLS handshake, Client key exchange (16):
} [data not shown]
* SSLv3, TLS change cipher, Client hello (1):
} [data not shown]
* SSLv3, TLS handshake, Finished (20):
} [data not shown]
* SSLv3, TLS change cipher, Client hello (1):
{ [data not shown]
* SSLv3, TLS handshake, Finished (20):
{ [data not shown]
* SSL connection using ECDHE-RSA-AES128-GCM-SHA256
* Server certificate:
* 	 subject: C=US; ST=California; L=San Francisco; O=GitHub, Inc.; CN=*.github.com
* 	 start date: 2017-01-18 00:00:00 GMT
* 	 expire date: 2020-04-17 12:00:00 GMT
* 	 subjectAltName: api.github.com matched
* 	 issuer: C=US; O=DigiCert Inc; OU=www.digicert.com; CN=DigiCert SHA2 High Assurance Server CA
* 	 SSL certificate verify ok.
> GET /repos/codacy/codacy-coverage-reporter/releases/latest HTTP/1.1
> User-Agent: curl/7.35.0
> Host: api.github.com
> Accept: */*
> 
< HTTP/1.1 403 Forbidden
* Server GitHub.com is not blacklisted
< Server: GitHub.com
< Date: Thu, 15 Mar 2018 11:56:41 GMT
< Content-Type: application/json; charset=utf-8
< Content-Length: 258
< Status: 403 Forbidden
< X-RateLimit-Limit: 60
< X-RateLimit-Remaining: 0
< X-RateLimit-Reset: 1521115871
< X-GitHub-Media-Type: github.v3; format=json
< Access-Control-Expose-Headers: ETag, Link, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval
< Access-Control-Allow-Origin: *
< Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
< X-Frame-Options: deny
< X-Content-Type-Options: nosniff
< X-XSS-Protection: 1; mode=block
< Referrer-Policy: origin-when-cross-origin, strict-origin-when-cross-origin
< Content-Security-Policy: default-src 'none'
< X-Runtime-rack: 0.011464
< X-GitHub-Request-Id: 8EC0:5064:E00A50:1D9E488:5AAA5F79
< 
{ [data not shown]
* Connection #0 to host api.github.com left intact
--2018-03-15 11:56:41--  http://null/
Resolving null (null)... failed: Name or service not known.
wget: unable to resolve host address ‘null’
```

**Comment by rtfpessoa** [comment]
@rshivane this is definitely a problem. You can try something in the lines of https://github.com/codacy/codacy-coverage-reporter/pull/77/files. I will try to update the readme soon.

**Comment by rshivane** [comment]
@rtfpessoa I had considered this option of reading maven manifest.xml from sonatype. At that time the latest release in the manifest file was pointing v3 which was unstable instead of pointing to the stable v2. Since then, v4 has been released and that seems to be a stable release.

Before making the switch, can you confirm that going forward when you make pre-releases/unstable-releases to maven, the manfiest release will still point to the latest stable release?

**Comment by rtfpessoa** [comment]
Usually we do not change much in this plugin. But I am not sure I can confirm that.
Ideally you should use a fixed version and then update manually.

If you are using the latest is always a complicated to assure no apis will change. What you can do is use 4.x.x and that way I will not break the api.

**Comment by rshivane** [comment]
Thanks @rtfpessoa, using latest 4.x.x from maven manifest would work great for us. 
Will update our Travis config accordingly

**Comment by freemo** [comment]
@rtfpessoa BTW I too get this issue. It causes travis to fail about half the time. I am trying your suggested fix as well. I will update you if it works.

**Comment by freemo** [comment]
@rtfpessoa Nope, doing as the readme suggests results in the following error:

```
0.01s$ java -jar ~/codacy-coverage-reporter-assembly-latest.jar -l Java -r target/site/jacoco/jacoco.xml
Error: Unable to access jarfile /home/travis/codacy-coverage-reporter-assembly-latest.jar
```

**Comment by freemo** [comment]
@rtfpessoa BTW the above issue was that the "-latest" part shouldnt be there (a typo in the diff). After fixing that I get the following error instead.

```
Unrecognized argument: -l
```

**Comment by freemo** [comment]
@rtfpessoa OK so i think i finally found it, there was another typo in the readme you linked it should have been 

```
java -jar ~/codacy-coverage-reporter-assembly-latest.jar report -l Java -r target/site/jacoco/jacoco.xml
```

It was missing the word report. This was also in my travis from before the issue so must have been an issue with some earlier documentation too.

**Comment by freemo** [comment]
@rtfpessoa I'd like to report NOW everything is finally working with my above comments taken into consideration and based off of the diff you linked. With that said I'd like to know if this is just a workaround or a perminant fix? If a more appropriate fix will be coming later will you update this ticket with the fix or is there a more appropriate place I can subscribe? This has been a thorn in my side for a while So I'd like to get the solution right.

**Comment by rtfpessoa** [comment]
Hi @freemo the issues you referred should all be related to the fact that version 4.0.0 broke compatibility and the README was updated. If you find any issue in the current README let me know.

Regarding the original issue in this thread we still do not have a final fix.

**Comment by benmccann** [comment]
I was getting this a lot:

> The command "wget --timeout=120 --retry-connrefused -O ~/codacy-coverage-reporter-assembly-latest.jar $(curl https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r .assets[0].browser_download_url)" failed and exited with 4 during .

Hardcoding the version to 4.0.1 seemed to have fixed it: https://github.com/jtablesaw/tablesaw/commit/c0784f078b999155e3211746ea4ac72409ba4d80

**Comment by manuel-hegner** [comment]
Maybe as a proposal for fairer solution to github and travis codacy could publish its jar to maven central with a pom file within it?
This would allow us to use `mvn exec:java com.codacy:codacy-coverage-reporter:LATEST` and thus use travis caching in an easy way.

**Comment by benmccann** [comment]
@rtfpessoa if I run `curl -o codacy-coverage-reporter "https://dl.bintray.com/codacy/Binaries/$(curl https://api.bintray.com/packages/codacy/Binaries/codacy-coverage-reporter/versions/_latest | jq -r .name)/codacy-coverage-reporter"
chmod u+x codacy-coverage-reporter` then I get an empty file

However, if I run `curl -o codacy-coverage-reporter "$(curl https://circleci.com/api/v1.1/project/github/codacy/codacy-coverage-reporter/latest/artifacts | jq -r .[0].url)"` then I do get output

**Comment by benmccann** [comment]
Hmm, though it seems that one fails at the next step:
```
$ curl -o ~/codacy-coverage-reporter "$(curl https://circleci.com/api/v1.1/project/github/codacy/codacy-coverage-reporter/latest/artifacts | jq -r .[0].url)"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   280  100   280    0     0    301      0 --:--:-- --:--:-- --:--:--   301
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 19.9M    0 19.9M    0     0   227k      0 --:--:--  0:01:29 --:--:--  187k
$ java -cp ~/codacy-coverage-reporter report --language Java --coverage-report aggregate/target/site/jacoco-aggregate/jacoco.xml
Error: Could not find or load main class report
```

**Comment by rtfpessoa** [comment]
@benmccann thanks for letting me know. Seems like something is weird while publishing. Will check.

**Comment by rtfpessoa** [comment]
Fixed in #94, Bintray command was not following redirects. 
Had to remove CircleCI option (explained in there).

**Comment by rtfpessoa** [comment]
@benmccann also just noticed in your command there is an issue.
If you use the linux binary you do not need java.
You can run just `codacy-coverage-reporter report ...`

**Comment by OsamaFelFel** [comment]
I figured a better way to do it through maven. The plugin already on maven central and I have no idea why it's not documented. I added the following to my pom

<dependency>

    <groupId>com.codacy</groupId>
    <artifactId>codacy-coverage-reporter</artifactId>
    <version>4.0.2</version>
    <scope>test</scope>
</dependency>


------------

                <plugins>

                    <plugin>
                        <groupId>org.jacoco</groupId>
                        <artifactId>jacoco-maven-plugin</artifactId>
                        <version>0.8.1</version>
                        <executions>
                            <execution>
                                <goals>
                                    <goal>prepare-agent</goal>
                                </goals>
                            </execution>
                            <execution>
                                <id>report</id>
                                <phase>test</phase>
                                <goals>
                                    <goal>report</goal>
                                </goals>
                                <configuration>
                                    <outputDirectory>target/reports/jacoco-ut/</outputDirectory>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                    <plugin>
                        <groupId>org.codehaus.mojo</groupId>
                        <artifactId>exec-maven-plugin</artifactId>
                        <version>1.6.0</version>
                        <executions>
                            <execution>
                                <phase>test</phase>
                                <goals>
                                    <goal>java</goal>
                                </goals>
                                <configuration>
                                    <mainClass>com.codacy.CodacyCoverageReporter</mainClass>
                                    <arguments>
                                        <argument>report</argument>
                                        <argument>-l</argument>
                                        <argument>Java</argument>
                                        <argument>-r</argument>
                                        <argument>target/reports/jacoco-ut/jacoco.xml</argument>
                                    </arguments>
                                    <classpathScope>test</classpathScope>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>

**Comment by rtfpessoa** [comment]
@OsamaFelFel there is a badge in the README with the maven central version, but I guess we never suggest that option since it did not seem the best way to use.

I will try adding your suggestion to the readme.

**Comment by OsamaFelFel** [comment]
@rtfpessoa can I ask why do you think it's not the best way? I believe this solution eliminate multiple problems. Beside the github api limitation, this solution guarantees the coverage will be uploaded. If travis ( for example ) failed while uploading the report the whole build will fail. That behavior won't be achieved without custom script on travis.

On a side note, if you are going to move this into README, you should remove the original section related to Maven.

**Comment by benmccann** [comment]
@rtfpessoa it's still not working for me. [Now I'm getting](https://travis-ci.org/jtablesaw/tablesaw/builds/410821002?utm_source=github_status&utm_medium=notification):

>0.01s$ ./codacy-coverage-reporter report --language Java --coverage-report aggregate/target/site/jacoco-aggregate/jacoco.xml
08/01 13:57:52 ERROR c.c.rules.ConfigurationRules:22 - Invalid configuration: Invalid CODACY_API_BASE_URL: https://api.codacy.com
()

**Comment by rtfpessoa** [comment]
@OsamaFelFel my point about not being ideal was regarding using the dependency programatically.

Since you can do a plugin like you have it makes more sense.

**Comment by rtfpessoa** [comment]
There was a problem in the tests and they were not being run as expected. This lead to a buggy release. Sorry about this. I will try to fix it soon but seems like a limitation from the tool I was using to release the binary. I will try to find an alternative for the jar in the meanwhile.

Sorry for the confusion.

**Comment by manuel-hegner** [comment]
A good solution for us was to use
`mvn com.googlecode.maven-download-plugin:download-maven-plugin:1.4.1:artifact -DgroupId="com.codacy" -DartifactId="codacy-coverage-reporter" -Dversion=LATEST -DoutputFileName="codacy.jar" -DoutputDirectory="./"` to download the latest jar. This will also use the .m2 local repository so that you can easily travis cache it.target/site/jacoco/jacoco.xml`

**Comment by rtfpessoa** [comment]
Fixed in https://github.com/codacy/codacy-coverage-reporter/releases/tag/6.0.0
