### ISSUE TITLE
codacy-coverage-reporter prints wrong version

### ISSUE THREAD

**Issue by pedrorijo91** [codacy/codacy-coverage-reporter#8]
When running with --help flag, it prints 

```
codacy-coverage-reporter 1.0.0
Usage: codacy-coverage-reporter [options]

  -l <value> | --language <value>
        foo is an integer property
  -t <value> | --projectToken <value>
        your project API token
  -r <value> | --coverageReport <value>
        your project API token
  --codacyApiBaseUrl <value>
        the base URL for the Codacy API
  --prefix <value>
        the project path prefix
  --help
        prints this usage text
```

When the actual version is 1.0.4
This version should be fetched from the pom or something. This way you have to manually change in every release

https://github.com/codacy/codacy-coverage-reporter/blob/master/src/main/scala/com/codacy/CodacyCoverageReporter.scala#L65

**Comment by pedrorijo91** [comment]
http://stackoverflow.com/questions/2712970/get-maven-artifact-version-at-runtime

**Comment by pedrorijo91** [comment]
http://stackoverflow.com/questions/8957025/sbt-including-the-version-number-in-a-program

**Comment by machadoit** [comment]
It will be included when the version number is well defined during the automated build process
