### ISSUE TITLE
Code for Travis provided in documentation doesn't work anymore

### ISSUE THREAD

**Issue by straumat** [codacy/codacy-coverage-reporter#85]
In the documentation, you wrote : 
`wget -O ~/codacy-coverage-reporter-assembly-latest.jar $(curl https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r .assets[0].browser_download_url)`

But it doesn't seem to work anymore.

**Comment by rtfpessoa** [comment]
@straumat there was an issue with the release it should work again now.

**Comment by straumat** [comment]
It works. Thanks
