### ISSUE TITLE
Error with the gradle task

### ISSUE THREAD

**Issue by Sylhare** [codacy/codacy-coverage-reporter#86]
## Setup

MacOS 10.10

JDK OpenJDK 1.8.0_152

Gradle 4.4

### Library Dependencies

Jacoco

### Expected Behavior

Please describe the expected behavior of the issue, starting from the first action.

1. Use the gradle task to send coverage

### Actual Behavior

Got an error, seems like the link for the dependency does not provide the codacy plugin so it's trying the other one. Did you move something since the date of the solution? Is there a new dependency link I should use?

```
> Task :sendCoverageToCodacy FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':sendCoverageToCodacy'.
> Could not resolve all files for configuration ':codacy'.
   > Could not resolve com.github.codacy:codacy-coverage-reporter:4.0.1.
     Required by:
         project :
      > Skipped due to earlier error
      > Could not resolve com.github.codacy:codacy-coverage-reporter:4.0.1.
         > Could not get resource 'https://jitpack.io/com/github/codacy/codacy-coverage-reporter/4.0.1/codacy-coverage-reporter-4.0.1.pom'.
            > Could not GET 'https://jitpack.io/com/github/codacy/codacy-coverage-reporter/4.0.1/codacy-coverage-reporter-4.0.1.pom'.
               > Connect to 172.25.175.88:80 [/172.25.175.88] failed: connect timed out

```

### Reproducible Test Case

Try the gradle task from #39.
The other one is even worse and fail from the start.

Thanks

**Comment by rtfpessoa** [comment]
hi @Sylhare, that seems weird becausd `https://jitpack.io/com/github/codacy/codacy-coverage-reporter/4.0.1/codacy-coverage-reporter-4.0.1.pom` is actually returning a valid pom.

I am not very familiar with gradle, so I would say it might have been a temporary issue with connectivity or from jitpack.


Can you try again?

**Comment by Sylhare** [comment]
Ah so I have messed around with my IDE a little and it seemed that I managed to get the package. So the url is good indeed.
It seems to be working fine now.

Note that I had replaced `-SNAPSHOT` to the current version `4.0.1` from what the readme said.

Thanks for your help, I am closing this issue now 😉
