### ISSUE TITLE
Question: Aggregated coverage for maven multi module project 

### ISSUE THREAD

**Issue by davidgoate** [codacy/codacy-coverage-reporter#88]
### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)

Linux 4.14.33-51.34.amzn1.x86_64 #1  x86_64 GNU/Linux

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)

Oracle 10.0.1

### Expected Behavior

Aggregated coverage report for multi module project is uploaded

### Actual Behavior

I think I'm only seeing the coverage report of the very last module that runs in the build. Is there a specific JaCoCo file I should upload in the case of a multi module project (as opposed to the jacoco file of each module).

**Comment by rtfpessoa** [comment]
Currently this tool does not support merging of reports directly but you can check `Multiple coverage reports for the same language` section in the README and either send all the reports or use a maven plugin to aggregate before sending.
