### ISSUE TITLE
Revert changes in latest release

### ISSUE THREAD

**Issue by aharonha** [codacy/codacy-coverage-reporter#97]
In https://github.com/codacy/codacy-coverage-reporter/releases/tag/5.0.275 it seems that the latest release is buggy.
Please do a release on a latest working version.
Our deployment and integration scripts in Travis always download your latest release (even if it is buggy!)

**Comment by rtfpessoa** [comment]
Version 5 is a pre-release. It should not be a problem.
Can you check if there is something in the way you get the version to avoid this problem?

I could delete it from GitHub but the version would be in the maven repos and people would not see the warning.
