### ISSUE TITLE
No asset attached to latest release

### ISSUE THREAD

**Issue by olanb7** [codacy/codacy-coverage-reporter#99]
We have a script which pulls the latest codacy plugin as part of a cicd flow. This uses the latest release, pulling it from your github release. The latest release has no attached jar file so our CICD flow breaks.

### Expected Behavior

https://github.com/codacy/codacy-coverage-reporter/releases/tag/4.0.3 has a downloadable asset.

https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest has a `browser_download_url` in the assets array field.

### Actual Behavior

https://github.com/codacy/codacy-coverage-reporter/releases/tag/4.0.3 has no asset attached, as similar releases do.

**Comment by rtfpessoa** [comment]
@olanb7 Thanks for the heads up. Fixing ongoing.

**Comment by rtfpessoa** [comment]
Fixed.
